.ldep scheme: object code archive dependencies are constructed so that when a library is updated, the executables that build from this lib will be considered out of date and re-built.  Because the LDFLAGS may differ between execs, each has its own dependency constructed in $(LOGIN_ARCH)/exec.ldep.
new:
GNU Makefile functionality, $(call name,arg[s]), is used to greatly
simplify code and improve readability

diff --git a/config/Makefile.extended b/config/Makefile.extended
--- a/config/Makefile.extended
+++ b/config/Makefile.extended
@@ -1,8 +1,8 @@
 ##########################################################################
 ##########################################################################
 # Define those files recognized by make
-.SUFFIXES:
-.SUFFIXES: .o .c .C .f .h .dep .odep
+
+.SUFFIXES: .o .c .C .f .h .dep .sdep .ldep
 
 .PRECIOUS: ${LOGIN_ARCH}/%.o
 
@@ -15,6 +15,34 @@ SHELL = /bin/sh
 ##########################################################################
 ##########################################################################
 
+
+##########################################################################
+# these variables define a number of useful functions
+##########################################################################
+
+# converts a list of source code file names to object code filenames
+src2obj = ${patsubst %.c,%.o,${patsubst %.f,%.o,${patsubst %.C,%.o,$(1)}}}
+
+# converts a list of source code file names to executable filenames
+src2bin = ${patsubst %.c,%,${patsubst %.f,%,${patsubst %.C,%,$(1)}}}
+
+# filters the archive names out of $(1)
+lib.l = $(patsubst -l%,lib%.a,$(filter -l%,$(1)))
+
+# filters the library paths out of $(1)
+lib.L = $(subst -L,,$(filter -L%,$(1)))
+
+# finds the first instance of the file, $(1), in the list of paths, $(2)
+firstpath = $(firstword $(wildcard $(addsuffix /$(1), $(2))))
+
+# finds the first archive in each of the library paths of $(1)
+lib_deps = $(foreach l,$(lib.l),$(call firstpath,$(l),$(call lib.L,$(1))))
+
+# set the list of archives on which the general executable depends 
+libraries := $(call lib_deps,$(LDFLAGS))
+
+
+
 ##########################################################################
 # The following lines create the BINS macro, upon which the "all" target 
 # depends and the EXECUTABLES macro used in the calculation of the
@@ -23,11 +51,13 @@ SHELL = /bin/sh
 ##########################################################################
 # Add programs to executables (PROGRAMS lists the source code,
 # from which the extensions must be stripped).
-EXECS := ${patsubst %.c,%,${patsubst %.f,%,${patsubst %.C,%,${PROGRAMS}}}}
+EXECS := $(call src2bin,$(PROGRAMS))
 EXECUTABLES += $(EXECS)
 
 # define bin path executables
 BINS:=$(EXECUTABLES:%=$(BINDIR)/%)
+
+
 
 ##########################################################################
 # The following lines create the SRC_DEPS macro,
@@ -38,7 +68,7 @@ BINS:=$(EXECUTABLES:%=$(BINDIR)/%)
 
 # expand each exec.srcs macro to e.g. exec.srcs"blah.c more.C"
 SRCS_EXP := $(foreach exec,$(EXECUTABLES),$(exec).srcs\"${$(exec).srcs}\")
-# strip out those expansions with empty ""
+# filter out those expansions with empty ""
 SRCS_CLEAN := $(strip $(filter-out %\"\",$(SRCS_EXP)))
 # now select those exec.srcs strings left
 SRCS_INCLUDE := $(filter %.srcs,$(subst \", ,$(SRCS_CLEAN)))
@@ -47,6 +77,8 @@ SRC_DEPS := $(SRCS_INCLUDE:%.srcs=./$(LOGIN_ARCH)/%.sdep)
 
 # now filter out the exec.srcs strings and remove repeats
 OTHER_SRCS += $(sort $(filter-out %.srcs,$(subst \", ,$(SRCS_CLEAN))))
+
+
 
 ##########################################################################
 # The ALL_SRCS macro determines for which files makedepend will be called
@@ -63,6 +95,8 @@ OTHER_SRCS += $(sort $(filter-out %.srcs,$(subst \", ,$(SRCS_CLEAN))))
 all_srcs := ${LIB_SRCS} ${PROGRAMS} ${TESTS} ${OTHER_SRCS}
 ALL_SRCS := ${filter-out moc_%.C, ${all_srcs}}
 
+
+
 ##########################################################################
 # The following lines create the DEPS macro, upon which the Makefile 
 # depends. (unless MAKEDEP=no)  Dependencies are built only for C/C++ code
@@ -73,6 +107,8 @@ DEP_c_SRCS := ${filter %.c, $(DEP_SRCS)}
 
 DEPS := ${DEP_C_SRCS:%.C=./$(LOGIN_ARCH)/%.dep} \
 	${DEP_c_SRCS:%.c=./$(LOGIN_ARCH)/%.dep}
+
+
 
 ##########################################################################
 # The following lines create the INCS macro,
@@ -101,10 +137,12 @@ LIBS:=${LIBRARIES:%=$(LIBDIR)/%}
 # upon which the "test" target depends...
 # TESTS and TESTEXECS macros are previously defined in the user Makefile
 ##########################################################################
-TEXECS := ${patsubst %.c,%,${patsubst %.f,%,${patsubst %.C,%,${TESTS}}}}
+TEXECS := $(call src2bin,$(TESTS))
 TESTEXECS += $(TEXECS)
 
 RUNTESTS:=$(TESTEXECS:%=%.runtest)
+
+
 
 ##########################################################################
 # Flags specified to makedepend
@@ -115,12 +153,17 @@ ifeq ($(PSRGTKMM),yes)
 MDFLAGS += -DGTK_MAJOR_VERSION=2 # makedepend is stupid
 endif
 
+
+
 ##########################################################################
 # The INSTALL_INCS, INSTALL_SHXS, INSTALL_LIBS and INSTALL_BINS macros
 # are constructed in a separate Makefile that specializes in installations
 ##########################################################################
 make_install := $(LOCAL_ROOT)/include/Makefile.install
 include $(make_install)
+
+
+
 
 ##########################################################################
 ##########################################################################
@@ -154,6 +197,8 @@ define header_depend
 @$(RM) $@.tmp
 endef
 
+
+
 ##########################################################################
 # Implicit rule to clean up .dep files that reference header files have 
 # been moved or no longer exist where previously found.  This should make
@@ -167,23 +212,45 @@ define remove_outdated_deps
 $(GREP) $@ ${LOGIN_ARCH}/*.dep | $(AWK) -F: '{print "rm -rf "$$1}' | sh
 endef
 
+
+
 ##########################################################################
-# Implicit rule to make the source file dependency list in the appropriate
+# Implicit rule to make the object code dependency list in the appropriate
 # architecture specific subdirectory.  These files depend on the Makefile,
 # as their information is changed only when the link information changes.
 ##########################################################################
-$(LOGIN_ARCH)/%.sdep: %.srcs Makefile
+
+# returns the list of object code files for a specific executable, $(1)
+srcs = $(addprefix ${LOGIN_ARCH}/, $(call src2obj,$($(1).srcs)))
+
+$(LOGIN_ARCH)/%.sdep: Makefile
 	@echo source depend: $*
+	@echo "$*.OBJS := $(call srcs,$*)" > ${LOGIN_ARCH}/$*.sdep;
+	@echo "${BINDIR}/$*: $$($*.OBJS)" >> ${LOGIN_ARCH}/$*.sdep;
 
-SRC2OBJ := sed -e 's/\.c/\.o/g' -e 's/\.C/\.o/g' -e 's/\.f/\.o/g'
 
-# This implicit rule is actually a phony target, as it does not create
-# a file of the same name
-%.srcs:
-	@srcdep_file=$(@:%.srcs=${LOGIN_ARCH}/%.sdep); \
-	OBJS=`echo "$($@:%=${LOGIN_ARCH}/%)" | $(SRC2OBJ)`; \
-	echo "$(@:%.srcs=%.OBJS) := $$OBJS" > $$srcdep_file; \
-	echo "$(@:%.srcs=${BINDIR}/%): $$OBJS" >> $$srcdep_file;
+
+##########################################################################
+# The following defines the LIB_DEPS macro, and the list of .ldep files
+# upon which the Makefile depends.  Each file contains a list of the
+# archive files upon which each executable depends.  Executables may be 
+# built using different LDFLAGS.  When a library in the LDFLAGS list is 
+# updated, the executable will be considered out of date and re-made.
+##########################################################################
+
+LIB_DEPS := $(EXECUTABLES:%=./$(LOGIN_ARCH)/%.ldep)
+
+# returns the list of archives on which a specific executable, $(1), depends
+# this function should be called in the shell.
+define eval_libs
+if [ "$(origin $(1).LDFLAGS)" = "undefined" ]; then echo $(libraries); \
+else echo $(call lib_deps,$($(1).LDFLAGS)); fi
+endef
+
+$(LOGIN_ARCH)/%.ldep:
+	@echo "${BINDIR}/$*: $(shell $(call eval_libs,$*))" > $@;
+
+
 
 ##########################################################################
 # Implicit rules to make an object code file in the appropriate 
@@ -199,8 +266,10 @@ $(LOGIN_ARCH)/%.o: %.C $(LOGIN_ARCH)/.exists
 $(LOGIN_ARCH)/%.o: %.f $(LOGIN_ARCH)/.exists
 	$(FC) ${INCFLAGS} ${FFLAGS} ${CPPFLAGS} -c -o $@ $<
 
+
+
 ##########################################################################
-# this macro creates the source code that defines the variables declared
+# MakeInfo creates the source code that defines the variables declared
 # in MakeInfo.h
 ##########################################################################
 
@@ -215,54 +284,46 @@ if [ ! -z "`grep MakeInfo\.h $*.[cC]`" ]; then \
 fi
 endef
 
+
+
 ##########################################################################
 # Rules to make (link) an executable (for example: 'exec') 
 # made up of the object file of the same name (exec.o) and, optionally,
 # object files listed in the exec.OBJS macro.  This macro is defined in
-# ${LOGIN_ARCH}/exec.odep included by Makefile.extended when the
+# ${LOGIN_ARCH}/exec.sdep, included by Makefile.extended when the
 # exec.srcs macro is defined in the user's makefile.
 #
 # The file is linked with LDFLAGS, or exec.LDFLAGS, if defined.
 ##########################################################################
 
-# filter out the paths specified by the user
-libdirs := $(subst -L,,$(filter -L%,$(LDFLAGS)))
-# filter out the static archives specified by the user
-lfilt := ${patsubst -l%,\%lib%.a,$(filter -l%,$(LDFLAGS))}
-# find existing archive files
-ex_libs := $(foreach dir,$(libdirs),$(shell echo $(dir)/*.a 2> /dev/null))
-# the library in this module takes preference over existing libs
-all_libs := $(LIBDIR)/$(LIBRARY) $(ex_libs)
-libraries := $(foreach l,$(lfilt),$(firstword $(filter $l,$(all_libs))))
-
 define check_exec
 if [ ! -x $@ ]; then \
-echo "Cleaning up failed compilation: $@"; ($(RM) $@ && exit 1); \
+  echo "Cleaning up failed compilation: $@"; ($(RM) $@ && exit 1); \
 fi
 endef
 
 define eval_LDFLAGS
 if [ ! -z "`grep MakeInfo\.h $*.[cC]`" ]; then echo $(MakeInfo.o); fi; \
-if [ "$($*.LDFLAGS)" = "NONE" ]; then echo ""; \
-elif [ -z "$($*.LDFLAGS)" ]; then echo $(LDFLAGS); \
+if [ "$(origin $*.LDFLAGS)" = "undefined" ]; then echo $(LDFLAGS); \
 else echo $($*.LDFLAGS); fi
 endef
 
-$(BINDIR)/%: $(LOGIN_ARCH)/%.o %.C $(libraries) $(LIBDIR)/$(LIBRARY)
+$(BINDIR)/%: $(LOGIN_ARCH)/%.o %.C
 	@$(MakeInfo)
 	-$(CCC) ${CCFLAGS} -o $@ $< $($*.OBJS) $(shell $(eval_LDFLAGS))
 	@rm -f $(MakeInfo.c) $(MakeInfo.o)
 	@$(check_exec)
 
-$(BINDIR)/%: $(LOGIN_ARCH)/%.o %.c $(libraries) $(LIBDIR)/$(LIBRARY)
+$(BINDIR)/%: $(LOGIN_ARCH)/%.o %.c
 	@$(MakeInfo)
 	-$(CC) ${CFLAGS} -o $@ $< $($*.OBJS) $(shell $(eval_LDFLAGS))
 	@rm -f $(MakeInfo.c) $(MakeInfo.o)
 	@$(check_exec)
 
-$(BINDIR)/%: $(LOGIN_ARCH)/%.o %.f $(libraries) $(LIBDIR)/$(LIBRARY)
+$(BINDIR)/%: $(LOGIN_ARCH)/%.o %.f
 	-$(FC) ${FFLAGS} -o $@ $< $($*.OBJS) $(shell $(eval_LDFLAGS))
 	@$(check_exec)
+
 
 
 ##########################################################################
@@ -282,10 +343,12 @@ $(BINDIR)/%: $(LOGIN_ARCH)/%.o %.f $(libraries) $(LIBDIR)/$(LIBRARY)
 moc_%.C: %.h
 	$(QTMOC) $< -o $@
 
+
+
 ##########################################################################
 # Rule to make the standard targets "phony".  eg. no file 'all'
 ##########################################################################
-.PHONY: ${TARGETS} error %.srcs %.runtest
+.PHONY: ${TARGETS} error %.runtest
 
 ##########################################################################
 # Check for any errors
@@ -419,7 +482,7 @@ endif # install_yes != install
 
 ONELIB := $(LIBDIR)/$(LIBRARY)
 
-LOBJS:=$(patsubst %.c,%.o,$(patsubst %.f,%.o,$(patsubst %.C,%.o,$(LIB_SRCS))))
+LOBJS := $(call src2obj,$(LIB_SRCS))
 LIB_OBJS := $(LOBJS:%=$(LOGIN_ARCH)/%)
 
 $(ONELIB) : $(LIB_OBJS)
@@ -446,6 +509,8 @@ ifneq ($(SRC_DEPS),)
 -include $(SRC_DEPS)
 endif
 
+-include $(LIB_DEPS)
+
 ifneq (${strip $(MAKEDEP)},no)
 ifneq ($(DEPS),)
 -include $(DEPS)
@@ -455,9 +520,9 @@ endif # MAKEDEP != no
 endif # autodepend == yes
 
 ##########################################################################
-# Rules to ensure that directories are created before attempts to
-# place files in them are made.  These should remain last in the file,
-# lest they interfere with $< expansion
+# Rules to ensure that directories are created before making attempts to
+# place files in them.  These should remain last in the file, lest they
+# interfere with $< expansion
 ##########################################################################
 $(DEPS) $(SRC_DEPS): $(LOGIN_ARCH)/.exists
 $(INCS): $(INCDIR)/.exists
